---
ExcelDataDriven:
    Filepath: C:\Users\Administrator\Desktop\test.xlsx
    TestSheet:  test
Mysql:
    Type:
    Host:
    Port:
    User:
    Password:
Http:
    Host: http://api.wenxianghao.hapn.cc
Mail:
    Host:
    Port:
    From_address:
    To_address:
    Mail_pass:

