---
DataDriven:
  - excel:
       filePath: C:\Users\Administrator\Desktop\test.xlsx
       testSheet:  test
  - mysql:
       type:
       host:
       port:
       user:
       password:
Http:
    Host: http://api.jh.hunbasha.cn
Mail:
    Host:
    Port:
    From_address:
    To_address:
    Mail_pass:
Log:
    Path: E:\apiLog\api.log
